### ISSUE TITLE
[Bug]: When I run npm run generate, it is failing to generate png files in the middle, saying selected element undefined.

### ISSUE THREAD

**Issue by KodisBabu** [codeSTACKr/minter-dapp#40]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

/mnt/d/codeStackrNFT/backend/src/main.js:182
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at /mnt/d/codeStackrNFT/backend/src/main.js:182:61
    at new Promise (<anonymous>)
    at loadLayerImg (/mnt/d/codeStackrNFT/backend/src/main.js:180:10)
    at /mnt/d/codeStackrNFT/backend/src/main.js:362:31
    at Array.forEach (<anonymous>)
    at startCreating (/mnt/d/codeStackrNFT/backend/src/main.js:361:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Protect your information

- [X] I Agree

**Comment by codeSTACKr** [comment]
This is not a bug. The `path` issue is a result of either your configuration not being correct, not saved, or your layer folder/file names containing special characters. For the names, you should only use a-z, 0-1, and spaces. Do not use dashes, slashes, or any other special characters.

**Comment by STREETFIENDZ** [comment]
I had the same issue just now, @codeSTACKr your comment worked for me ! Thank you sir
