### ISSUE TITLE
[Bug]: Unsupported Image Type

### ISSUE THREAD

**Issue by nixks** [codeSTACKr/minter-dapp#60]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

Hi @codeSTACKr ,

And thank you for the amazing work so far!

I am facing a situation where the "run generate" command begins the procedure of creating the images but somewhere in the process, totally random, it stops with the following error:

Error: Unsupported image type
    at setSource (C:\Users\User\Downloads\NFT\10k\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\User\Downloads\NFT\10k\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\User\Downloads\NFT\10k\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\User\Downloads\NFT\10k\node_modules\canvas\index.js:23:10)
    at C:\Users\User\Downloads\NFT\10k\src\main.js:184:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\User\Downloads\NFT\10k\src\main.js:183:10)
    at C:\Users\User\Downloads\NFT\10k\src\main.js:364:31
    at Array.forEach (<anonymous>)

### What have you tried?

I have tried multiple times the procedure from the beginning and in different software versions and I always find this error. I have even created new layers just to test and still get that error. File and folder names are carefully named, no special characters at all. Only the hashtag for the rarity is used.

### Protect your information

- [x] I Agree

**Comment by nixks** [comment]
For those who may have found the same issue,

follow the steps found here: https://github.com/HashLips/hashlips_art_engine/issues/615

As it looks like it has something to do with the hashlips canvas and how the images overall are exported.

For me passing all the images through an online converter, either size or type, did the trick.
